# Generated by Django 3.2.18 on 2023-02-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptiongw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptionkey',
            name='encryption_key',
        ),
        migrations.AddField(
            model_name='encryptionkey',
            name='encryption_private_key',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='encryptionkey',
            name='encryption_public_key',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
