# Generated by Django 3.2.18 on 2023-02-27 04:40

import django.core.files.storage
from django.db import migrations, models
import encryptiongw.models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptiongw', '0002_auto_20230220_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypteddata',
            name='qrcode',
            field=models.FileField(max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/encryption_gw/private-media/'), upload_to=encryptiongw.models.store_qr_code),
        ),
    ]
