# Generated by Django 3.2.18 on 2023-02-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptiongw', '0006_keyregenerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyregenerate',
            name='encryption_bit',
            field=models.IntegerField(default=2048),
        ),
    ]
