# Generated by Django 3.2.18 on 2023-02-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptiongw', '0008_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
