# Generated by Django 3.2.18 on 2023-03-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptiongw', '0009_device_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
